#端口号
server:
  port: 9000
#服务名称
spring:
  application:
    name: api-gateway

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#自定义路由映射
zuul:
  routes:
    order-service: /apigateway/order/**
    product-service: /apigateway/product/**
  #统一入口为上面的配置，其他入口忽略
  ignored-patterns: /*-service/**
  #处理http请求头为空的问题，获取不到cookie问题
  sensitive-headers:
  #忽略整个服务，不对外提供接口
  #ignored-services: product-service

